# Example Detectron2 config for parts model (5 classes)
_BASE_: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 5
DATASETS:
  TRAIN: ("parts_train",)
  TEST: ("parts_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 3000
OUTPUT_DIR: "./weights/parts_model"
